#!/usr/bin/env python3
"""
Extract COPR repository information from build info YAML files.

This script reads the YAML files generated by obal scratch builds
(when build_package_archive_build_info=True) and extracts repository
URLs and distribution information for use in repoclosure testing.

Equivalent to the copr_repos() function from theforeman/jenkins-jobs.

Usage:
    # Output as JSON (default)
    ./extract_copr_repos.py mypackage

    # Output as bash-friendly format (one repo per line: URL DIST)
    ./extract_copr_repos.py --bash mypackage

    # Quiet mode (no error messages if file not found)
    ./extract_copr_repos.py --quiet mypackage
"""

import sys
import os
import json
import argparse
import urllib.request
import urllib.error


COPR_API_URL = "https://copr.fedorainfracloud.org/api_3"


def fetch_copr_build_info(build_id):
    """
    Fetch build details from COPR API to get owner and project names.

    Args:
        build_id: COPR build ID (e.g., "10591897")

    Returns:
        Tuple of (ownername, projectname) or None on failure
    """
    url = f"{COPR_API_URL}/build/{build_id}"
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            data = json.loads(resp.read())
            owner = data.get('ownername', '').lstrip('@')
            project = data.get('projectname', '')
            if owner and project:
                return (owner, project)
    except (urllib.error.URLError, json.JSONDecodeError, KeyError):
        pass
    return None


def convert_to_dist(chroot):
    """
    Convert COPR chroot identifier to distribution shorthand.

    Examples:
        "rhel-8-x86_64" -> "el8"
        "centos-stream-9-x86_64" -> "el9"
        "opensuse-leap-15.4-x86_64" -> "leap154"

    Args:
        chroot: COPR chroot string (e.g., "rhel-8-x86_64")

    Returns:
        Distribution shorthand (e.g., "el8")
    """
    family_map = {
        'rhel': 'el',
        'centos-stream': 'el',
        'opensuse-leap': 'leap'
    }

    chroot_parts = chroot.split('-')
    # Everything except last 2 parts (version and arch)
    os_family = '-'.join(chroot_parts[:-2])
    # Second-to-last part is version, remove dots
    version = chroot_parts[-2].replace('.', '')

    dist_prefix = family_map.get(os_family, os_family)
    return f"{dist_prefix}{version}"


def extract_copr_repos(package_name, quiet=False):
    """
    Extract COPR repository information from build info YAML file.

    Args:
        package_name: Name of the package (matches YAML filename)
        quiet: Suppress error messages if file not found

    Returns:
        List of dicts with 'url' and 'dist' keys, or empty list if not found
    """
    repos = []

    yaml_path = f'copr_build_info/{package_name}'

    if not os.path.exists('copr_build_info'):
        if not quiet:
            print("Error: copr_build_info directory not found", file=sys.stderr)
            print("Hint: Run obal scratch with -e build_package_archive_build_info=True", file=sys.stderr)
        return repos

    if not os.path.exists(yaml_path):
        if not quiet:
            print(f"Error: {yaml_path} not found", file=sys.stderr)
            print(f"Hint: Ensure scratch build completed successfully for {package_name}", file=sys.stderr)
        return repos

    try:
        import yaml
    except ImportError:
        print("Error: PyYAML not available", file=sys.stderr)
        print("Install with: pip install PyYAML", file=sys.stderr)
        sys.exit(1)

    with open(yaml_path, 'r') as f:
        try:
            build_info_yaml = yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"Error: Failed to parse YAML: {e}", file=sys.stderr)
            return repos

    # Extract repository information from each build result
    for build_info in build_info_yaml.get('results', []):
        try:
            chroot = build_info['chroot']
            user = None
            project = None

            # Format 1: direct user/project fields (obal with updated copr_build module)
            if 'user' in build_info and 'project' in build_info:
                user = build_info['user']
                project = build_info['project']
            # Format 2: invocation.module_args (older Ansible versions)
            elif 'invocation' in build_info:
                module_args = build_info['invocation']['module_args']
                user = module_args['user']
                project = module_args['project']
            # Format 3: COPR API lookup using build ID (fallback)
            else:
                build_ids = build_info.get('builds', [])
                if not build_ids:
                    if not quiet:
                        print(f"Warning: No build IDs found for chroot {chroot}", file=sys.stderr)
                    continue
                api_result = fetch_copr_build_info(build_ids[0])
                if not api_result:
                    if not quiet:
                        print(f"Warning: Could not fetch COPR build info for build {build_ids[0]}", file=sys.stderr)
                    continue
                user, project = api_result

            repo_url = (
                f"https://download.copr.fedorainfracloud.org/results/"
                f"{user}/{project}/{chroot}"
            )

            repos.append({
                'url': repo_url,
                'dist': convert_to_dist(chroot),
                'chroot': chroot
            })
        except (KeyError, TypeError) as e:
            if not quiet:
                print(f"Warning: Skipping malformed build info entry: {e}", file=sys.stderr)
            continue

    return repos


def main():
    parser = argparse.ArgumentParser(
        description='Extract COPR repository URLs from build info files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        'package',
        help='Package name (matches YAML filename in copr_build_info/)'
    )
    parser.add_argument(
        '--bash',
        action='store_true',
        help='Output in bash-friendly format (URL DIST per line)'
    )
    parser.add_argument(
        '--quiet', '-q',
        action='store_true',
        help='Suppress error messages if file not found'
    )

    args = parser.parse_args()

    repos = extract_copr_repos(args.package, quiet=args.quiet)

    if not repos:
        sys.exit(1 if not args.quiet else 0)

    if args.bash:
        # Output format: URL DIST (one per line, easy to parse in bash)
        for repo in repos:
            print(f"{repo['url']} {repo['dist']}")
    else:
        # Output as JSON (default)
        print(json.dumps(repos, indent=2))


if __name__ == '__main__':
    main()